### ISSUE TITLE
goclone: command not found

### ISSUE THREAD

**Issue by JFLuz** [goclone-dev/goclone#70]
I think i did all the steps:
1> Installed GO and added the PATH environment variable on $HOME/.profile
    go version go1.21.6 linux/amd64

2> Did the manual installation of goclone
    go install github.com/imthaghost/goclone/cmd/goclone@latest

3> Then tried the 'goclone <example.com>' and got the "command not found" message.

What am i missing?
Thanks!

**Comment by X0LUV** [comment]
I’m running across the same issue. The command `go get` has been deprecated. 
now if you use ` go install github.com/imthaghost/goclone/cmd/goclone@latest ` you’ll probably see in the logs this errors.
```

/usr/local/go/src/math/acosh.go:43:6: Acosh defined in both Go and assembly
/usr/local/go/src/math/asin.go:20:6: Asin defined in both Go and assembly
/usr/local/go/src/math/asin.go:58:6: Acos defined in both Go and assembly
/usr/local/go/src/math/asinh.go:40:6: Asinh defined in both Go and assembly
/usr/local/go/src/math/atan.go:96:6: Atan defined in both Go and assembly
/usr/local/go/src/math/atan2.go:30:6: Atan2 defined in both Go and assembly
/usr/local/go/src/math/atanh.go:48:6: Atanh defined in both Go and assembly
/usr/local/go/src/math/cbrt.go:26:6: Cbrt defined in both Go and assembly
/usr/local/go/src/math/erf.go:189:6: Erf defined in both Go and assembly
/usr/local/go/src/math/erf.go:274:6: Erfc defined in both Go and assembly
/usr/local/go/src/math/erf.go:274:6: too many errors

```

BTW I’m running Ubuntu 20.04 LTS. The go documentation does not show a work around. 

I also tried doing the installation through brew and the installation gets killed.

```

x0luv@goclone:~$ brew install goclone
==> Fetching imthaghost/goclone/goclone
==> Downloading https://github.com/imthaghost/goclone/releases/download/v1.2.0/goclone_1.2.0_Linux-64bit.tar.gz
Already downloaded: /home/x0luv/.cache/Homebrew/downloads/bf0099db9dc9ca0b0d8f52a2ef9067b4356afeec621ba7953c06aa62ba8979b6--goclone_1.2.0_Linux-64bit.tar.gz
==> Installing goclone from imthaghost/goclone
Killed
x0luv@goclone:~$ /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:256:in `rescue in <main>': private method `puts' called for nil:NilClass (NoMethodError)
        from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:217:in `<main>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:221:in `initialize': Connection refused - connect(2) for /tmp/homebrew20240217-31495-ubmwe5/socket (Errno::ECONNREFUSED)
        from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:221:in `open'
        from /home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/build.rb:221:in `<main>'

```

**Comment by elcafe7** [comment]
Running on MacOS. Brew would not install it so I downloaded Go from their website and was able to get it to install, but trying to use the goclone command gives me:
`zsh: command not found: goclone`

**Comment by ghost** [comment]
also broken for me

**Comment by hunter0014** [comment]
run with same error "goclone: command not found" anyone can help us plz.

**Comment by mesaglio** [comment]
Can you test with `go install github.com/imthaghost/goclone/cmd/goclone@v1.2.1`

```terminal
❯ go install github.com/imthaghost/goclone/cmd/goclone@v1.2.1
❯ goclone
Usage:
  goclone <url> [flags]

Flags:
  -C, --cookie strings        Pre-set these cookies
  -h, --help                  help for goclone
  -o, --open                  Automatically open project in deafult browser
  -p, --proxy_string string   Proxy connection string. Support http and socks5 https://pkg.go.dev/github.com/gocolly/colly#Collector.SetProxy
  -s, --serve                 Serve the generated files using Echo.
  -P, --servePort int         Serve port number. (default 5000)
  -u, --user_agent string     Custom User Agent
```

**Comment by mesaglio** [comment]
Could anyone test my comment to vlaidar if it works?

**Comment by OhBobb** [comment]
> Could anyone test my comment to vlaidar if it works?

i ran in to same issues as above but im on windows so this is what i ended up doing:

when i ran this command:
```
# Go version >= 1.20
go install github.com/goclone-dev/goclone/cmd/goclone@latest
```

i got this error:
```
go: github.com/goclone-dev/goclone/cmd/goclone@latest: version constraints conflict:
        github.com/goclone-dev/goclone@v1.2.1: parsing go.mod:
        module declares its path as: github.com/imthaghost/goclone
                but was required as: github.com/goclone-dev/goclone
```

when i ran the 'manual' commands:
```
# Clone the repository
git clone https://github.com/goclone-dev/goclone.git
cd goclone
# Build and run
go build -o goclone cmd/goclone/main.go
```
i got this error when i ran 'goclone':
```
'goclone' is not recognized as an internal or external command,
operable program or batch file.
```

when i ran this command:
```
go install github.com/imthaghost/goclone/cmd/goclone@v1.2.1
```

i got this error when i ran 'goclone':
```
'goclone' is not recognized as an internal or external command,
operable program or batch file.
```

all the above was done within miniconda env on windows 10

i then switched to wsl ubuntu 22.04 and created a miniconda env and ran this command:
```
go install github.com/imthaghost/goclone/cmd/goclone@v1.2.1
```

and got this error when i ran 'goclone':
```
goclone: command not found
```

i then ran the 'manual' steps:
```
# Clone the repository
git clone https://github.com/goclone-dev/goclone.git
cd goclone
# Build and run
go build -o goclone cmd/goclone/main.go
```

and go this error when i ran 'goclone':
```
goclone: command not found
```

i then ran this command:
```
sudo mv goclone /usr/local/bin/
```

and it worked! all the wsl commands i also created a miniconda env within wsl. so i guess the trick is to make sure goclone is mv to /usr/local/bin after running the 'manual' steps

also, im not big fan of using wsl(cus of disk space usage and im poor on disk space right now) so i figured out that if you use this command(after git clone this repo and ignoring the 'build' command) within miniconda env in windows:
```
go run cmd/goclone/main.go https://your-fav-website-to-copy
``` 
it should work

sorry for long reply. i just wanted to be clear( i hope i was?) on how i managed to make it work and help anyone else with this issue. thanks for your work btw!

**Comment by mcgigglepop** [comment]
Not sure if anyone is still having issues, but what's happening here is that `go build -o goclone cmd/goclone/main.go` builds a binary that you can execute called `goclone`. the reason why it's not finding the `goclone` command is probably because you haven't added it to your system via `mv goclone /usr/local/bin/` (a directory that’s usually in your `$PATH`)

You can do a few things. You can move it there, or, if you prefer just make it executable and execute it from the directory in which it is built (i.e. the cloned repo):

`chmod +x ./goclone`
`./goclone HTTPS://WEBSITE-TO-CLONE.COM`

These are commands for bash so if you're using powershell or something, you would have to adjust. This should fix your issue about `goclone: command not found`. Cheers.

**Comment by mesaglio** [comment]
Pls see https://github.com/goclone-dev/goclone/issues/96#issuecomment-3203786098
